project:
  type: website
  output-dir: docs
  preview:
    browser: false
    timeout: 0.001

website:
  title: "Predictive Ecology Community"
  description: "The Predictive Ecology Community website"
  favicon: "assets/logo/favicon-32x32.png"
  navbar:
    logo: "assets/logo/favicon-196x196.png"
    search: true
    right:
      - href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: Projects.qmd
      - SpaDES.qmd
      - Workshops.qmd
      - text: "Training"
        menu:
          - text: "Training Book"
            href: training/_book/index.html
          - text: "Other training resources"
            href: otherTraining.qmd
      - Manuals.qmd
      - publications.qmd
      - presentations.qmd
      - icon: github
        href: https://github.com/PredictiveEcology
      - icon: twitter
        href: https://twitter.com/PredictiveEcol
  page-footer:
    left:
      - text: "This site is maintained by E. McIntire and C. Barros, with contributions by A. Chubaty, T. Micheletti and others. Powered by Quarto"
  sidebar:
    logo: "assets/logo/favicon-196x196.png"
  comments:
      hypothesis:
        theme: clean
        openSidebar: false
  # If you are forking our repo to develop content please disable our Google Analytics tag during development.
  # If building your own site, replace our GA tag with your own GA tag before deployment.
  # This will prevent your activity being tracked and counted in our analytics dashboard.
  # Thank you!
  google-analytics: "G-1689MGK5S2"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: assets/css/main.scss
    smooth-scroll: true
    link-external-newwindow: true

editor: visual

execute:
  freeze: auto
